BINARY := bin/labcheck
PKG := ./cmd/labcheck

SCRIPT_NAME := smx2-checker
INSTALL_DIR := $(HOME)/.local/bin

.PHONY: build run watch fmt vet clean install uninstall

build:
	@mkdir -p bin
	go build -o $(BINARY) $(PKG)

run: build
	./$(BINARY)

# Builds the binary and drops a small wrapper script named smx2-checker into
# ~/.local/bin (no sudo required). The wrapper hard-codes this checkout's
# absolute path, so it keeps working from any directory but breaks if the
# checkout is later moved — re-run "make install" after moving it.
install: build
	@mkdir -p "$(INSTALL_DIR)"
	@repo="$$(pwd)"; \
	printf '%s\n' \
		'#!/usr/bin/env bash' \
		"# Generated by \"make install\" from $$repo - rerun after moving the checkout." \
		"export LABCHECK_ACTIVITIES_DIR=\"$$repo/activitats\"" \
		"exec \"$$repo/$(BINARY)\" \"\$$@\"" \
		> "$(INSTALL_DIR)/$(SCRIPT_NAME)"; \
	chmod +x "$(INSTALL_DIR)/$(SCRIPT_NAME)"
	@echo "Installed: $(INSTALL_DIR)/$(SCRIPT_NAME)"
	@case ":$$PATH:" in \
		*":$(INSTALL_DIR):"*) echo "Run it with: $(SCRIPT_NAME)" ;; \
		*) printf '\n%s is not on your PATH yet.\nAdd this line to ~/.bashrc, then open a new terminal:\n\n    export PATH="$$HOME/.local/bin:$$PATH"\n\n' "$(INSTALL_DIR)" ;; \
	esac

uninstall:
	rm -f "$(INSTALL_DIR)/$(SCRIPT_NAME)"
	@echo "Removed $(INSTALL_DIR)/$(SCRIPT_NAME)"

# Rebuilds the executable every time a .go file changes. Requires entr
# (apt install entr). If you add a new .go file, restart `make watch` so
# it picks it up — entr only watches the files it was started with.
watch:
	@mkdir -p bin
	find . -name '*.go' -not -path './bin/*' | entr sh -c \
		'go build -o $(BINARY) $(PKG) && echo "[$$(date +%H:%M:%S)] build ok -> $(BINARY)" || echo "[$$(date +%H:%M:%S)] build failed"'

fmt:
	gofmt -l .

vet:
	go vet ./...

clean:
	rm -rf bin
